//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.WithholdingTax.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T1.B1.WithholdingTax.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;HCO_FWT0100&quot; FormType=&quot;HCO_FWT0100&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;-1&quot; title=&quot;Grupos de municipios&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;343&quot; height=&quot;357&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;HCO_FWT0100&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;actio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GruposMunicipios {
            get {
                return ResourceManager.GetString("GruposMunicipios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Menu String=&quot;Autoretenciones&quot; Enabled=&quot;1&quot; Position=&quot;1&quot; Checked=&quot;0&quot; FatherUID=&quot;HCO_M001&quot; Image=&quot;&quot; Type=&quot;2&quot; UniqueID=&quot;HCO_M002&quot;/&gt;
        ///&lt;Menu String=&quot;Configuración&quot; Enabled=&quot;1&quot; Position=&quot;1&quot; Checked=&quot;0&quot; FatherUID=&quot;HCO_M002&quot; Image=&quot;&quot; Type=&quot;2&quot; UniqueID=&quot;HCO_M003&quot;/&gt;
        ///&lt;Menu String=&quot;Herramientas&quot; Enabled=&quot;1&quot; Position=&quot;2&quot; Checked=&quot;0&quot; FatherUID=&quot;HCO_M002&quot; Image=&quot;&quot; Type=&quot;2&quot; UniqueID=&quot;HCO_M004&quot;/&gt;
        ///&lt;Menu String=&quot;Informes&quot; Enabled=&quot;1&quot; Position=&quot;3&quot; Checked=&quot;0&quot; FatherUID=&quot;HCO_M002&quot; Image=&quot;&quot; Type=&quot;2&quot; UniqueID=&quot;HCO_M005&quot;/&gt;.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM
        ///(SELECT &quot;DocEntry&quot;,
        ///		&quot;DocNum&quot; AS &quot;Numero&quot;,
        ///		&quot;CardCode&quot; AS &quot;Socio de Negocio&quot;,
        ///		&apos;Factura Proveedor&apos; AS &quot;Documento&quot;,
        ///		&quot;DocTotal&quot; AS &quot;Total del Documento&quot;  
        ///		FROM OPCH WHERE &quot;DocEntry&quot; NOT IN ( SELECT DISTINCT &quot;U_DOCENTRY&quot; 
        ///												FROM &quot;@HCO_T1WHT400&quot;
        ///												WHERE &quot;U_DOCTYPE&quot; = 18) 
        ///												AND &quot;ObjType&quot;=18 AND &quot;DocEntry&quot; IN (SELECT DISTINCT &quot;AbsEntry&quot; FROM PCH5)
        ///                                                UNION ALL
        ///                                                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MissingOper {
            get {
                return ResourceManager.GetString("MissingOper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;HCO_FWT1100&quot; FormType=&quot;HCO_FWT1100&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;-1&quot; title=&quot;Registro de retenciones&quot; visible=&quot;1&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;600&quot; height=&quot;414&quot; client_width=&quot;492&quot; client_height=&quot;299&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;HCO_FWT1100&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegistroRetenciones {
            get {
                return ResourceManager.GetString("RegistroRetenciones", resourceCulture);
            }
        }
    }
}
