//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.SelfWithholdingTax {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SWTaxResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SWTaxResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T1.B1.SelfWithholdingTax.SWTaxResources", typeof(SWTaxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;[--FormType--]&quot; FormType=&quot;[--FormType--]&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;[--UniqueId--]&quot; title=&quot;Cancelar Autoretenciones&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;576&quot; height=&quot;473&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;dtSelfWT&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CancelarAutoretenciones {
            get {
                return ResourceManager.GetString("CancelarAutoretenciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;HCO_FSW0100&quot; FormType=&quot;HCO_FSW0100&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;-1&quot; title=&quot;Autorretenciones&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;600&quot; height=&quot;417&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;HCO_FSW0100&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWTaxConfigForm {
            get {
                return ResourceManager.GetString("SWTaxConfigForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;update&quot;&gt;
        ///      &lt;form uid=&quot;[--UniqueId--]&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;action type=&quot;add&quot;&gt;
        ///              &lt;DataTable Uid=&quot;HCO_DSWT&quot;&gt;
        ///                &lt;Columns /&gt;
        ///              &lt;/DataTable&gt;
        ///            &lt;/action&gt;
        ///          &lt;/DataTables&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/dbdatasources&gt;
        ///          &lt;userdatasources&gt;
        ///            &lt;action type=&quot;add&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWTaxFolderDocuments {
            get {
                return ResourceManager.GetString("SWTaxFolderDocuments", resourceCulture);
            }
        }
    }
}
